export const crops={
    "Rice": 41,
    "Maize": 25,
    "Moong(Green Gram)": 28,
    "Urad": 53,
    "Groundnut": 18,
    "Sesamum": 44,
    "Potato": 38,
    "Sugarcane": 47,
    "Wheat": 54,
    "Rapeseed &Mustard": 40,
    "Bajra": 3,
    "Jowar": 21,
    "Arhar/Tur": 2,
    "Ragi": 39,
    "Gram": 17,
    "Small millets": 45,
    "Cotton(lint)": 12,
    "Onion": 32,
    "Sunflower": 48,
    "Dry chillies": 14,
    "Other Kharif pulses": 35,
    "Horse-gram": 20,
    "Peas & beans (Pulses)": 37,
    "Tobacco": 51,
    "Other Rabi pulses": 33,
    "Soyabean": 46,
    "Turmeric": 52,
    "Masoor": 26,
    "Ginger": 16,
    "Linseed": 24,
    "Castor seed": 9,
    "Barley": 5,
    "Sweet potato": 49,
    "Garlic": 15,
    "Banana": 4,
    "Mesta": 27,
    "Tapioca": 50,
    "Coriander": 11,
    "Niger seed": 30,
    "Jute": 22,
    "Coconut": 10,
    "Safflower": 42,
    "Arecanut": 1,
    "Sannhamp": 43,
    "Other Cereals": 34,
    "Cowpea(Lobia)": 13,
    "Cashewnut": 8,
    "Black pepper": 6,
    "other oilseeds": 55,
    "Moth": 29,
    "Khesari": 23,
    "Cardamom": 7,
    "Guar seed": 19,
    "Oilseeds total": 31,
    "Other Summer Pulses": 36
}
export const seasons={
    "Kharif": 2,
    "Rabi": 3,
    "Whole Year": 5,
    "Summer": 4,
    "Autumn": 1,
    "Winter": 6
}
export const states={
    "Karnataka": 13,
    "Andhra Pradesh": 1,
    "West Bengal": 30,
    "Chhattisgarh": 5,
    "Bihar": 4,
    "Madhya Pradesh": 15,
    "Uttar Pradesh": 28,
    "Tamil Nadu": 25,
    "Gujarat": 8,
    "Maharashtra": 16,
    "Uttarakhand": 29,
    "Odisha": 21,
    "Assam": 3,
    "Nagaland": 20,
    "Puducherry": 22,
    "Meghalaya": 18,
    "Haryana": 9,
    "Jammu and Kashmir": 11,
    "Himachal Pradesh": 10,
    "Kerala": 14,
    "Manipur": 17,
    "Tripura": 27,
    "Mizoram": 19,
    "Telangana": 26,
    "Punjab": 23,
    "Arunachal Pradesh": 2,
    "Jharkhand": 12,
    "Goa": 7,
    "Sikkim": 24,
    "Delhi": 6
}
